---
title: "politics team descriptive stats"
author: "Laura Sørine Voldgaard"
date: "2025-06-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# libraries
install.packages("pacman")
library(pacman)

pacman::p_load(tidyverse, dplyr, readxl, patchwork)

```

```{r}
getwd()
```


```{r}
# load data
data <- read_excel("data/data.xlsx", sheet = 1)
```


```{r}
# Replace NA values in 'income' with 5
data$income[is.na(data$income)] <- 5

```



Gender

```{r}
library(dplyr)

data %>%
  count(gender) %>%
  mutate(percentage = (n / sum(n)) * 100)

```



Age / birth
```{r}
# Get the current year
current_year <- as.numeric(format(Sys.Date(), "%Y"))

# Calculate age
data$age <- current_year - data$birth

# Compute mean and standard deviation
mean_age <- mean(data$age, na.rm = TRUE)
sd_age <- sd(data$age, na.rm = TRUE)

# Print results
cat("Mean age:", mean_age, "\n")
cat("Standard deviation of age:", sd_age, "\n")


```



Income
```{r}
# Compute mean and standard deviation for income
mean_income <- mean(data$income, na.rm = TRUE)
sd_income <- sd(data$income, na.rm = TRUE)

# Print results
cat("Mean income:", mean_income, "\n")
cat("Standard deviation of income:", sd_income, "\n")

```



Birth region
```{r}
# Frequencies for birth region
table(data$birth_rg)
prop.table(table(data$birth_rg)) * 100

# Frequencies for residence region
table(data$residence_rg)
prop.table(table(data$residence_rg)) * 100

```



